#!/bin/bash
IMAGE=docker.io/densukest/skrsql:v4.0.1
SVNAME=skrsql
USER=sql

check_running() {
    test $(podman container ps -a -f "status=running,name=$SVNAME" | wc -l) -gt 1
    return $?
}

case "$1" in
start)
    echo "staring server..."
    if check_running; then
        echo "already running"
    else
        # 稼働中の場合は除外しているので、非稼働コンテナでのチェックのみでOK
        test $(podman container ps -a -f "name=$SVNAME" | wc -l) -gt 1 && podman container rm $SVNAME
        podman run --name $SVNAME --rm -d "$IMAGE"
    fi
    ;;
status)
    check_running
    RC=$?
    if [ $RC = 0 ]; then
        R="running"
    else
        R="not running"
    fi
    echo "SVNAME server is ${R}"
    exit ${RC}
    ;;
stop)
    if ! check_running; then
        echo "server stopped already."
        exit 0
    fi
    echo "stopping server..."
    podman stop $SVNAME
    ;;
list|can|q|drill)
    if ! check_running; then
        $0 start
        echo "wait 3 seconds."
        sleep 3
    fi
    echo "send command $1"...
    podman exec -it -u ${USER} ${SVNAME} "$@"
    ;;
*)
    cat <<EOM
usage: sql COMMAND ARGS...

commands:
- start: start DB server
- stop: stop DB server
- status: check whether DB server is running
- list/can/q/drill ARGS...: run tool in server
EOM
    ;;
esac
