on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: fetch code
          uses: actions/checkout@v3
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_AUTH }}
        - name: build and push image
          run: |
            docker buildx create --name mybuilder --use
            docker buildx build --push -platform=linux/arm64,linux/amd64 -t densukest/skrsql:v3 env
